name: presentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Miniconda
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
        bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
        echo "::add-path::$HOME/miniconda/bin"
    - name: Install tectonic and biber
      run: |
        conda install -y -c conda-forge tectonic
        sudo apt-get update -y
        sudo apt-get install -y biber
    - name: Typeset presentation
      run: |
        tectonic --keep-intermediates --reruns 0 presentation.tex
        biber presentation
        tectonic presentation.tex
    - name: Archive presentation.pdf
      uses: actions/upload-artifact@v1
      with:
       name: presentation.pdf
       path: presentation.pdf
        